import "isInteger.bs"

namespace rodash
  ' /**
  ' * @name add
  ' * @description Adds two numbers
  ' * @param {Dymanic} augend - The first number in an addition
  ' * @param {Dymanic} addend - The second number in an addition
  ' * @return {Integer} Returns the total
  ' */
  function add(augend, addend)
    value = 0
    if rodash.isNumber(augend) then value += augend
    if rodash.isNumber(addend) then value += addend

    return value
  end function
end namespace