import "capitalize.bs"

namespace _
  function camelCase(value = "" as string)
    value = value.replace("-", " ").replace("_", " ")
    value = value.trim()
    valueArray = value.split(" ")
    responseValue = ""

    for i = 0 to valueArray.count() -1
      valueString = valueArray[i]

      if i = 0 then
        responseValue += lcase(valueString)
      else
        responseValue += _.capitalize(valueString)
      end if
    end for

    return responseValue
  end function
end namespace