namespace rodash
  function capitalize(value = "" as string)
    value = value.trim()
    valueArray = value.split("")
    responseValue = ""

    for i = 0 to valueArray.count() -1
      valueString = valueArray[i]

      if i = 0 then
        responseValue += ucase(valueString)
      else
        responseValue += lcase(valueString)
      end if
    end for

    return responseValue
  end function
end namespace