

namespace rodash
  ' /**
  ' * Divides two numbers
  ' * @param {Dynamic} dividend - The first number in a division
  ' * @param {Dynamic} divisor - The second number in a division
  ' * @returns {Integer} value - Returns the quotient
  ' */
  function divide(dividend = 0 as dynamic, divisor = 0 as dynamic) as dynamic
    if rodash.isNaN(dividend) OR rodash.isNaN(divisor) return 0
    if rodash.lte(divisor, 0) then return dividend

    return dividend / divisor
  end function
end namespace
