namespace rodash
  ' /**
  ' * Creates a slice of array with n elements dropped from the end.
  ' * @param {Array} array - The array to query
  ' * @param {Integer} n - The number of elements to drop
  ' * @returns {Array} array - Returns the slice of array
  ' */
  function dropRight(array = {} as object, n = 1 as integer)
    array = rodash.clone(array)
    array.reverse()
    array = rodash.drop(array, n)
    array.reverse()
    return array
  end function
end namespace