namespace rodash
  ' Checks if two values are equivalent.
  ' @since 0.0.21
  ' @category Lang
  ' @param {Dynamic} value - The value to compare.
  ' @param {Dynamic} other - The other value to compare.
  ' @returns {Boolean} Returns `true` if the values are equivalent, else `false`.
  ' @example
  ' rodash.eq(1, 1) // => true
  ' rodash.eq(1, 2) // => false
  function eq(value as Dynamic, other as Dynamic)
    return rodash.isEqual(value, other)
  end function
end namespace
