namespace rodash
  ' Flattens array a single level deep.
  ' @since 0.0.21
  ' @category Array
  ' @param {Array} array - The array to flatten
  ' @returns {Dynamic} Returns the new flattened array
  function flatten(array = [])
    returnArray = []
    for each item in array
      if type(item) = "roArray" then
        returnArray.append(item)
      else
        returnArray.push(item)
      end if
    end for
    return returnArray
  end function
end namespace
