namespace rodash
  ' Recursively flattens array.
  ' @since 0.0.21
  ' @category Array
  ' @param {Array} array - The array to flatten
  ' @returns {Dynamic} Returns the new flattened array
  function flattenDeep(array = [])
    returnArray = []
    for each item in array
      if type(item) = "roArray" then
        returnArray.append(rodash.flattenDeep(item))
      else
        returnArray.push(item)
      end if
    end for
    return returnArray
  end function
end namespace
