namespace rodash
  ' This method is like rodash.forIn except that it iterates over properties of object in the opposite order.
  ' @since 0.0.21
  ' @category Object
  ' @param {Dynamic} obj - The object to iterate over
  ' @param {Dynamic} iteratee - The function invoked per iteration
  ' @return {Object} Returns object
  function forInRight(obj = {} as object, iteratee = invalid as dynamic)
    return rodash.internal.baseForEach(obj, iteratee, "right", "omit")
  end function
end namespace
