namespace rodash
  ' Converts a number of seconds to a date object.
  ' @since 0.0.21
  ' @category Date
  ' @param {Number} numSeconds - The number of seconds to convert.
  ' @param {Boolean} asLocal - Whether to get the local date. Default is false.
  ' @returns {Object} The date objects.
  @inline
  function fromSeconds(numSeconds = 0 as Integer, asLocal = false as Boolean) as Object
    return rodash.internal.getDateObject(asLocal).fromSeconds(numSeconds)
  end function
end namespace
