namespace rodash
  ' * Converts a number of seconds to a date object.
  ' * @since 0.0.21
  ' * @category Date
  ' * @param {Number} numSeconds - The number of seconds to convert.
  ' * @returns {Object} - The date objects.
  function fromSeconds(numSeconds = 0 as integer) as object
    dateObj = rodash.internal.getDateObject()

    return {
      "utc": dateObj.utc.fromSeconds(numSeconds),
      "local": dateObj.local.fromSeconds(numSeconds)
    }
  end function
end namespace
