namespace rodash
  ' Converts an ISO 8601 string to a date object.
  ' @since 0.0.21
  ' @category Date
  ' @param {String} dateString - The date string to convert.
  ' @returns {Object} - The date objects.
  function fromISO8601String(dateString = "" as string) as object
    dateObj = rodash.internal.getDateObject()

    return {
      "utc": dateObj.utc.fromISO8601String(dateString),
      "local": dateObj.local.fromISO8601String(dateString)
    }
  end function
end namespace
