namespace rodash
  ' Converts an ISO 8601 string to a date object.
  ' @since 0.0.21
  ' @category Date
  ' @param {String} dateString - The date string to convert.
  ' @param {Boolean} asLocal - Whether to get the local date. Default is false.
  ' @returns {Object} The date object.
  @inline
  function fromISO8601String(dateString = "" as String, asLocal = false as Boolean) as Integer
    return rodash.internal.getDateObject(asLocal).fromISO8601String(dateString)
  end function
end namespace
