' TODO: Rewrite this due to scoping issue
namespace rodash
  ' * @ignore
  ' * Creates an array of function property names from own enumerable properties of object.
  ' * @category Object
  ' * @param {Dynamic} obj - The object to iterate over
  ' * @return {Object} Returns object
  function functions(obj = {} as object)
    ' return rodash.base.forEach.baseForEach(obj, invalid, "left", "only")
    return []
  end function
end namespace