' TODO: Rewrite this due to scoping issue
namespace rodash
  ' /**

  ' * Creates an array of function property names from own and inherited enumerable properties of object.
  ' * @param {Dynamic} obj - The object to iterate over
  ' * @return {Object} Returns object
  ' */
  function functionsIn(obj = {} as object)
    ' return rodash.base.forEach.baseForEach(obj, invalid, "left", "only")
    return []
  end function
end namespace