namespace rodash
  ' Gets the last day of the month.
  ' @since 0.0.21
  ' @category Date
  ' @param {Boolean} asLocal - Whether to get the local last day of the month. Default is false.
  ' @returns {Integer} The last day of the month.
  @inline
  function getLastDayOfMonth(asLocal = false as Boolean) as Integer
    return rodash.internal.getDateObject(asLocal).getLastDayOfMonth()
  end function
end namespace
