namespace rodash
  ' Checks if the supplied value is a valid AssociativeArray type
  ' @since 0.0.21
  ' @category Lang
  ' @param {Dynamic} value The variable to be checked
  ' @returns {Boolean} Results of the check
  ' @example
  ' rodash.isAA({}) // => true
  ' rodash.isAA([]) // => false
  @inline
  function isAA(value as Dynamic) as Boolean
    return type(value) = "roAssociativeArray"
  end function
end namespace
