namespace rodash
  ' Checks if the supplied value is a valid Array type
  ' @since 0.0.21
  ' @category Lang
  ' @param {Dynamic} value The variable to be checked
  ' @returns {Boolean} Results of the check
  ' @example
  ' rodash.isArray([]) // => true
  ' rodash.isArray({}) // => false
  ' rodash.isArray("") // => false
  @inline
  function isArray(value as Dynamic) as Boolean
    return type(value) = "roArray"
  end function
end namespace
