import "isNonEmptyAA.bs"
import "isNonEmptyArray.bs"
import "isNonEmptyString.bs"

namespace _
  ' /**
  ' * @name isArrayLike
  ' * @description Checks if the supplied value is a valid unempty Array like type
  ' * @param {Dynamic} value The variable to be checked
  ' * @return {Boolean} Results of the check
  ' */
  function isArrayLike(value as dynamic)
    return _.isNonEmptyArray(value) OR _.isNonEmptyAA(value) OR _.isNonEmptyString(value)
  end function
end namespace