namespace rodash
  ' Checks if a value is empty.
  ' @since 0.0.21
  ' @category Lang
  ' @param {Dynamic} value The variable to be checked
  ' @returns {Boolean} Results of the check
  ' @example
  ' rodash.isEmpty("") // => true
  ' rodash.isEmpty([]) // => true
  ' rodash.isEmpty({}) // => true
  ' rodash.isEmpty(0) // => true
  ' rodash.isEmpty(false) // => true
  ' rodash.isEmpty(invalid) // => true
  ' rodash.isEmpty("Hello") // => false
  function isEmpty(value as Dynamic)
    if rodash.isInvalid(value) then
      return true
    else if rodash.isNumber(value)
      return value = 0
    else if rodash.isBoolean(value)
      return NOT value
    else if rodash.isNode(value) OR rodash.isFunction(value)
      return false
    else
      return value.isEmpty()
    end if

    return true
  end function
end namespace
