namespace rodash
  ' Checks if `value` is a finite primitive number.
  ' @since 0.0.21
  ' @category Lang
  function isFinite(value as dynamic) as boolean
    if NOT rodash.isNumber(value) then return false
    constants = rodash.internal.getConstants()

    if rodash.gt(value, constants.max_int) OR rodash.lt(value, constants.min_int) then return false

    return true
  end function
end namespace
