namespace rodash
  ' Checks if the supplied value is a valid Integer type
  ' @since 0.0.21
  ' @category Lang
  ' @param {Dynamic} value The variable to be checked
  ' @return {Boolean} Results of the check
  @inline
  function isInteger(value as Dynamic) as boolean
    return type(value) = "Integer" OR type(value) = "roInt" OR type(value) = "roInteger" OR type(value) = "LongInteger"
  end function
end namespace
