namespace rodash
  ' Checks if the supplied value is a valid String type and is not empty
  ' @since 0.0.21
  ' @category Lang
  ' @param {Dynamic} value The variable to be checked
  ' @returns {Boolean} Results of the check
  @inline
  function isNonEmptyString(value as Dynamic) as Boolean
    return (type(value) = "String" OR type(value) = "roString") AND NOT value.isEmpty()
  end function
end namespace
