namespace rodash
  ' Converts all elements in array into a string separated by separator.
  ' @since 0.0.21
  ' @category Array
  ' @param {Array} array - The array to convert
  ' @param {String} separator - The element separator
  ' @return {Array} Returns the joined string
  @inline
  function join(array = CreateObject("roArray", 0, true) as object, separator = "" as string)
    return rodash.clone(array).join(separator)
  end function
end namespace
