namespace rodash
  ' Computes the maximum value of array. If array is empty or falsey, invalid is returned.
  ' @since 0.0.21
  ' @category Math
  ' @param {Array} array - The array to iterate over
  ' @returns {Dynamic} Returns the maximum value
  ' @example
  ' rodash.max([4, 2, 8, 6]) // => 8
  @inline
  function max(array = CreateObject("roArray", 0, true) as Object) as Dynamic
    return rodash.maxBy(array)
  end function
end namespace
