namespace rodash
  ' Gets the number of milliseconds that have elapsed since the Unix epoch (1 January 1970 00:00:00 UTC).
  ' @since 0.0.21
  ' @category Date
  ' @returns {Longinteger} The number of milliseconds that have elapsed since the Unix epoch.
  function now() as Longinteger
    dateObj = rodash.internal.getDateObject()
    seconds& = dateObj.AsSeconds()
    milliseconds& = seconds& * 1000
    return milliseconds& + dateObj.GetMilliseconds()
  end function
end namespace
