namespace rodash
  ' Creates an array of shuffled values, using a version of the Fisher-Yates shuffle.
  ' @since 0.0.21
  ' @category Collection
  ' @param {Dynamic} collection - The collection to shuffle
  ' @return {Array} Returns the new shuffled array
  @inline
  function shuffle(collection = CreateObject("roArray", 0, true) as object)
    return rodash.sampleSize(collection, collection.count())
  end function
end namespace
