
namespace rodash
  ' /**

  ' * Check for the existence of a given sub string
  ' * @param {String} value The string to search
  ' * @param {String} subString The sub string to search for
  ' * @return {Boolean} Results of the search
  ' */
  function stringIncludes(value as String, subString as String) as Boolean
    return rodash.stringIndexOf(value, subString) > -1
  end function
end namespace
