namespace rodash
  ' Subtract two numbers.
  ' @since 0.0.21
  ' @category Math
  ' @param {Integer} minuend - The first number in a subtraction
  ' @param {Integer} subtrahend - The second number in a subtraction
  ' @returns {Integer} Returns the difference.
  function subtract(minuend as Dynamic, subtrahend as Dynamic) as Dynamic
    if rodash.isNaN(minuend) OR rodash.isNaN(subtrahend) return 0

    return minuend - subtrahend
  end function
end namespace
