namespace rodash
  ' Creates an array of unique values, in order, from all given arrays using SameValueZero for equality comparisons.
  ' @since 0.0.21
  ' @category Array
  ' @param {Array} arrays - The arrays to inspect
  ' @return {Object} Returns the new array of combined values
  function union(arrays = [] as object) as object
    return rodash.uniq(rodash.flattenDeep(arrays))
  end function
end namespace
