namespace rodash
  ' This method is like rodash.zipObject except that it supports property paths.
  ' @ignore
  ' @category Array
  ' @param {Array} array - The property identifiers
  ' @param {Array} values - The property values
  ' @return {Object} Returns the new object
  function zipObjectDeep(props = CreateObject("roArray", 0, true) as object, values = CreateObject("roArray", 0, true) as object) as object
    ' COME BACK
   end function
end namespace
