
namespace rodash.internal
  ' /**

  ' * @ignore
  ' * Attempts to convert the supplied value to a string.
  ' * @param {Dynamic} value The value to convert.
  ' * @return {String} Results of the conversion.
  ' */
  function arrayToString(array as Object) as String
    description = "["
    for each item in array
      description += rodash.toString(item) + ", "
    end for
    description = description.left(description.len() - 2) + "]"
    return description
  end function
end namespace
