
namespace rodash.internal
  ' @ignore
  function sanitizeKeyPath(value = "" as String)
    regex = createObject("roRegex", "\[(.*?)\]", "i")
    matches = regex.matchAll(value)

    if rodash.isNotInvalid(matches) then
      for each match in matches
        if rodash.isNotInvalid(match) then
          value = value.replace(match[0], "." + match[1])
        end if
      end for
    end if

    return 	value
  end function
end namespace
