namespace Tests
  @suite("RodashDateTests")
  class DateTests extends Rooibos.BaseTestSuite

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("Tests the rodash date methods")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("Test rodash date")
    function testNow()
      a = rodash.now()
      b = rodash.now()
      sleep(10)
      c = rodash.now()
      m.assertEqual(a, b)
      m.assertNotEqual(a, c)
    end function

  end class

end namespace
