namespace Tests
  @suite("RodashDateTests")
  class DateTests extends Rooibos.BaseTestSuite

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("Tests the rodash date methods")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("Test rodash date")
    function testNow()
      m.assertAAHasKeys(rodash.now(), ["local", "utc"])
    end function

  end class

end namespace
