' TESTS DISABLED FOR NOW AS ROOBIS APPEARS TO CHANGE THE SCOPE
' namespace Tests
'     @async
'     @SGNode("DummyNode")
'     @suite("RodashFunctionTests")
'     class FunctionTests extends rooibos.BaseTestSuite
'         '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'         @describe("Tests the rodash function methods")
'         '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'         @async
'         @it("delay")
'         function _()
'             rodash.delay(sub(context = invalid as dynamic)
'                 m.testSuite.done()
'             end sub)
'         end function

'         @async
'         @it("delay with duration")
'         function _()
'             rodash.delay(sub(context = invalid as dynamic)
'                 m.testSuite.done()
'             end sub, 10, invalid)
'         end function
'     end class
' end namespace
