namespace Tests
  @suite("RodashObjectTests")
  class ObjectTests extends Rooibos.BaseTestSuite

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("Tests the rodash object methods")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("get")
    @params({ "a": 1, "b": 2, "c": 1 }, "b", 2)
    @params({ "a": {"d": 3}, "b": 2, "c": 1 }, "a.d", 3)
    function _(obj as dynamic, path as dynamic, matchResult as dynamic)
      m.assertEqual(rodash.get(obj, path), matchResult)
    end function

    @it("invert")
    @params({ "a": 1, "b": 2, "c": 1 }, { "1": "c", "2": "b" })
    @params({ "c": 1, "a": 2, "b": 1 }, { "1": "c", "2": "a" })
    @params([], invalid)
    function _(itemOne as dynamic, matchResult as dynamic)
      m.assertEqual(rodash.invert(itemOne), matchResult)
    end function

    @it("omit")
    @params({ "a": 1, "b": "2", "c": 3 }, ["a", "c"], { "b": "2" })
    function _(object as dynamic, paths as dynamic, matchResult as dynamic)
      m.assertEqual(rodash.omit(object, paths), matchResult)
    end function

    @it("pick")
    @params({ "a": 1, "b": "2", "c": 3 }, ["a", "c"], { "a": 1, "c": 3 })
    function _(object as dynamic, paths as dynamic, matchResult as dynamic)
      m.assertEqual(rodash.pick(object, paths), matchResult)
    end function

  end class

end namespace
