namespace Tests
  @suite("RodashUtilsTests")
  class UtilsTests extends Rooibos.BaseTestSuite

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("Tests the rodash utils methods")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    @it("times")
    @params(1, ["0"])
    @params(2, ["0", "1"])
    @params(3, ["0", "1", "2"])
    function _(n as Integer, matchResult as Dynamic)
      m.assertEqual(rodash.times(n, rodash.toString), matchResult)
    end function

  end class

end namespace
