sub main(inputEvent as Object)
	? "inputEvent", inputEvent
	screen = createObject("roSGScreen")
	m.port = createObject("roMessagePort")
	screen.setMessagePort(m.port)
	scene = screen.CreateScene("MainScene")
	screen.show()' vscode_rdb_on_device_component_entry
	scene.observeField("closeApp", m.port)

	while true
		msg = wait(0, m.port)
		msgType = type(msg)

		if msgType = "roSGScreenEvent" then
			' Exit the main event loop resulting in the closure of the application
			if msg.isScreenClosed() then return
		else if msgType = "roSGNodeEvent" then
			field = msg.getField()
			' Exit the main event loop resulting in the closure of the application
			if field = "closeApp" then return
		end if
	end while
end sub
